# Generated by Django 4.1.2 on 2022-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('ET', 'Electronics and Communication Engineering'), ('EE', 'Electrical and Electronics Engineering')], max_length=10, null=True),
        ),
    ]
